### ISSUE TITLE
The path ../TPose/data_process/wholepose_features_extraction.py does not exist

### ISSUE THREAD

**Issue by kdafnis** [jackyjsy/data-prepare#1]
Thank you very much for providing the code. I am trying to use the data-prepare repo but the path to generate the pose features does not exist. Could you please provide me with the code?

Thanks in advance!

**Comment by jackyjsy** [comment]
Thanks for pointing out. I forgot to add pose feature in this repo. Now it has been added. Please check the [feature](https://github.com/jackyjsy/data-prepare/tree/main/feature) folder in this repo.
